import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Variable } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
      appearance={{
        variables: {
          colorText: "#fff",
          colorPrimary: "#830EF9",
          colorBackground: "#000000",
          colorInputBackground: "#1c1f2e",
          colorInputText: "#fff",
        }
      }}
      >
      <body className={`${inter.className} bg-mainb text-white`}>{children}</body>
      </ClerkProvider>
     
    </html>
  );
}
